<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>ES6中的Promise对象_Promise对象的catch方法</title>
  <script>
    const promise = new Promise((resolve, reject) => {
      setTimeout(() => {
        /**
         * 调用resolve()：设置promise对象的状态为成功状态，可以resolve()传递参数
         * 调用reject()： 设置promise对象的状态为失败状态，可以reject()传递参数
         */

        // let data = '数据库中的数据'
        // resolve(data)

        let error = '数据读取失败'
        reject(error)
      }, 1000)
    })

    /**
     * 使用catch()的解决promise调用出错
     */
    promise.catch(reason => {
      console.log(reason)
      return false
    })
  </script>
</head>

<body>

</body>

</html>